name: 'archlinux-ostree-encapsulate'
description: 'Deploys a container to ostree and re-encapsulates it.'
author: 'frap129'

# Define your inputs here.
inputs:
  image:
    description: 'Valid image in a container registry'
    required: true
    default: 'ghcr.io/frap129/trellis:testing'
  output-tar:
    description: 'Name of output tarball'
    required: false
    default: 'encapsulated.tar'

# Define your outputs here.
outputs:
  output-path:
    description: 'Path of the output tarball'

runs:
  using: docker
  image: Containerfile
  working-directory: ${{ github.action_path }}
  env:
    IMAGE: ${{ inputs.image }}
    OUTPUT_TAR: ${{ inputs.output-tar }}
